server:
  port: 9100
  tomcat:
    uri-encoding: UTF-8
    max-thread: 1000
spring:
  boot:
    admin:
      client:
        url: http://localhost:1000
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      # 采样率值介于0到1之间，1表示全部采集
#      probability: 1
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        # 主库数据源
        datasource:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: jdbc:oracle:thin:@localhost:1521:orcl
          username: administrator
          password: 123456
      seata: false    # 关闭seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭
 #关闭安全访问
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      

