spring:
  boot:
    admin:
      client:
        url: http://localhost:1000
#    zipkin:
#      base-url: http://localhost:9411
#    sleuth:
#      sampler:
#        # 采样率值介于0到1之间，1表示全部采集
#        probability: 1

# RabbitMQ相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
