server:
  port: 9527
eureka:
  instance:
    prefer-ip-address: true
    #eureka客户端多长时间发送心跳给eureka服务器，表明它仍然活着,默认30秒
    lease-renewal-interval-in-seconds: 5
    #eureka服务器在接受到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka.master.njcb.com.cn:6001/eureka
    #表示eureka client间隔多久去拉取服务器注册信息，默认30秒
    registry-fetch-interval-seconds: 30

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: cfc-rc
          uri: lb:/cfc-rc
          predicates:
            - Path=/cfc-rc/services/**
          filters:
            - StripPrefix=2
        - id: cfc-mbfe
          uri: lb://cfc-mbfe
          predicates:
            - Path=/njcb/**
          filters:
            - StripPrefix=1
      default-filters:
        - CircuitBreaker

# RabbitMQ相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#关闭安全访问
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
