spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: cfc-rc
          uri: lb:/cfc-rc
          predicates:
            - Path=/cfc-rc/services/**
          filters:
            - StripPrefix=2
        - id: cfc-mbfe
          uri: lb://cfc-mbfe
          predicates:
            - Path=/njcb/**
          filters:
            - StripPrefix=1
      default-filters:
        - CircuitBreaker

# RabbitMQ相关配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

#关闭安全访问
management:
security:
  enabled: false
endpoints:
  web:
    exposure:
      include: '*'
endpoint:
  health:
    show-details: always
